// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryApp.Migrations
{
    [DbContext(typeof(LibraryContext))]
    partial class LibraryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            Name = "George R.R. Martin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mark Twain"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = 6,
                            Name = "F. Scott Fitzgerald"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Toni Morrison"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Charles Dickens"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Virginia Woolf"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Harper Lee"
                        },
                        new
                        {
                            Id = 11,
                            Name = "H.G. Wells"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Isaac Asimov"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Arthur Conan Doyle"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Agatha Christie"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Leo Tolstoy"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Gabriel García Márquez"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Kurt Vonnegut"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Ray Bradbury"
                        },
                        new
                        {
                            Id = 20,
                            Name = "J.R.R. Tolkien"
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1,
                            Genre = "Fantasy",
                            Title = "Harry Potter and the Philosopher's Stone",
                            Year = 1997L
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 1,
                            Genre = "Fantasy",
                            Title = "Harry Potter and the Chamber of Secrets",
                            Year = 1998L
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 2,
                            Genre = "Fantasy",
                            Title = "A Game of Thrones",
                            Year = 1996L
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 2,
                            Genre = "Fantasy",
                            Title = "A Clash of Kings",
                            Year = 1998L
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 3,
                            Genre = "Romance",
                            Title = "Pride and Prejudice",
                            Year = 1813L
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 3,
                            Genre = "Romance",
                            Title = "Sense and Sensibility",
                            Year = 1811L
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 4,
                            Genre = "Adventure",
                            Title = "The Adventures of Tom Sawyer",
                            Year = 1876L
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 4,
                            Genre = "Adventure",
                            Title = "The Adventures of Huckleberry Finn",
                            Year = 1884L
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 5,
                            Genre = "Fiction",
                            Title = "The Old Man and the Sea",
                            Year = 1952L
                        },
                        new
                        {
                            Id = 10L,
                            AuthorId = 5,
                            Genre = "Fiction",
                            Title = "For Whom the Bell Tolls",
                            Year = 1940L
                        },
                        new
                        {
                            Id = 11L,
                            AuthorId = 6,
                            Genre = "Fiction",
                            Title = "The Great Gatsby",
                            Year = 1925L
                        },
                        new
                        {
                            Id = 12L,
                            AuthorId = 6,
                            Genre = "Fiction",
                            Title = "This Side of Paradise",
                            Year = 1920L
                        },
                        new
                        {
                            Id = 13L,
                            AuthorId = 7,
                            Genre = "Historical Fiction",
                            Title = "Beloved",
                            Year = 1987L
                        },
                        new
                        {
                            Id = 14L,
                            AuthorId = 7,
                            Genre = "Fiction",
                            Title = "Song of Solomon",
                            Year = 1977L
                        },
                        new
                        {
                            Id = 15L,
                            AuthorId = 8,
                            Genre = "Fiction",
                            Title = "Great Expectations",
                            Year = 1861L
                        },
                        new
                        {
                            Id = 16L,
                            AuthorId = 8,
                            Genre = "Fiction",
                            Title = "Oliver Twist",
                            Year = 1837L
                        },
                        new
                        {
                            Id = 17L,
                            AuthorId = 9,
                            Genre = "Fiction",
                            Title = "Mrs. Dalloway",
                            Year = 1925L
                        },
                        new
                        {
                            Id = 18L,
                            AuthorId = 9,
                            Genre = "Fiction",
                            Title = "To the Lighthouse",
                            Year = 1927L
                        },
                        new
                        {
                            Id = 19L,
                            AuthorId = 10,
                            Genre = "Fiction",
                            Title = "To Kill a Mockingbird",
                            Year = 1960L
                        },
                        new
                        {
                            Id = 20L,
                            AuthorId = 11,
                            Genre = "Science Fiction",
                            Title = "The War of the Worlds",
                            Year = 1898L
                        },
                        new
                        {
                            Id = 21L,
                            AuthorId = 11,
                            Genre = "Science Fiction",
                            Title = "The Time Machine",
                            Year = 1895L
                        },
                        new
                        {
                            Id = 22L,
                            AuthorId = 12,
                            Genre = "Science Fiction",
                            Title = "Foundation",
                            Year = 1951L
                        },
                        new
                        {
                            Id = 23L,
                            AuthorId = 12,
                            Genre = "Science Fiction",
                            Title = "I, Robot",
                            Year = 1950L
                        },
                        new
                        {
                            Id = 24L,
                            AuthorId = 13,
                            Genre = "Mystery",
                            Title = "Sherlock Holmes: A Study in Scarlet",
                            Year = 1887L
                        },
                        new
                        {
                            Id = 25L,
                            AuthorId = 13,
                            Genre = "Mystery",
                            Title = "The Hound of the Baskervilles",
                            Year = 1902L
                        },
                        new
                        {
                            Id = 26L,
                            AuthorId = 14,
                            Genre = "Mystery",
                            Title = "Murder on the Orient Express",
                            Year = 1934L
                        },
                        new
                        {
                            Id = 27L,
                            AuthorId = 14,
                            Genre = "Mystery",
                            Title = "The ABC Murders",
                            Year = 1936L
                        },
                        new
                        {
                            Id = 28L,
                            AuthorId = 15,
                            Genre = "Historical Fiction",
                            Title = "War and Peace",
                            Year = 1869L
                        },
                        new
                        {
                            Id = 29L,
                            AuthorId = 15,
                            Genre = "Romance",
                            Title = "Anna Karenina",
                            Year = 1877L
                        },
                        new
                        {
                            Id = 30L,
                            AuthorId = 16,
                            Genre = "Fiction",
                            Title = "Crime and Punishment",
                            Year = 1866L
                        },
                        new
                        {
                            Id = 31L,
                            AuthorId = 16,
                            Genre = "Fiction",
                            Title = "The Brothers Karamazov",
                            Year = 1880L
                        },
                        new
                        {
                            Id = 32L,
                            AuthorId = 17,
                            Genre = "Magical Realism",
                            Title = "One Hundred Years of Solitude",
                            Year = 1967L
                        },
                        new
                        {
                            Id = 33L,
                            AuthorId = 17,
                            Genre = "Fiction",
                            Title = "Chronicle of a Death Foretold",
                            Year = 1981L
                        },
                        new
                        {
                            Id = 34L,
                            AuthorId = 18,
                            Genre = "Science Fiction",
                            Title = "Slaughterhouse-Five",
                            Year = 1969L
                        },
                        new
                        {
                            Id = 35L,
                            AuthorId = 18,
                            Genre = "Science Fiction",
                            Title = "Cat's Cradle",
                            Year = 1963L
                        },
                        new
                        {
                            Id = 36L,
                            AuthorId = 19,
                            Genre = "Science Fiction",
                            Title = "Fahrenheit 451",
                            Year = 1953L
                        },
                        new
                        {
                            Id = 37L,
                            AuthorId = 19,
                            Genre = "Science Fiction",
                            Title = "The Martian Chronicles",
                            Year = 1950L
                        },
                        new
                        {
                            Id = 38L,
                            AuthorId = 20,
                            Genre = "Fantasy",
                            Title = "The Hobbit",
                            Year = 1937L
                        },
                        new
                        {
                            Id = 39L,
                            AuthorId = 20,
                            Genre = "Fantasy",
                            Title = "The Fellowship of the Ring",
                            Year = 1954L
                        },
                        new
                        {
                            Id = 40L,
                            AuthorId = 20,
                            Genre = "Fantasy",
                            Title = "The Two Towers",
                            Year = 1954L
                        });
                });

            modelBuilder.Entity("LibraryApp.Models.Book", b =>
                {
                    b.HasOne("LibraryApp.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryApp.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
